CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE COLLATE NOCASE,
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS poems (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  title TEXT NOT NULL CHECK (length(title) BETWEEN 1 AND 100),
  author TEXT NOT NULL CHECK (length(author) BETWEEN 1 AND 80),
  content TEXT NOT NULL CHECK (length(content) BETWEEN 1 AND 3000),
  category TEXT NOT NULL DEFAULT 'Sem categoria',
  source_url TEXT,
  is_seed INTEGER NOT NULL DEFAULT 0 CHECK (is_seed IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_poems_user_id ON poems (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_seed_source
  ON poems (source_url)
  WHERE is_seed = 1;
